// Domain types (see DESIGN.md §7). These mirror the API contract exactly.

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export type AttrValue = string | number | boolean;
export type Attributes = Record<string, AttrValue>;

// A validated log entry ready for persistence. `id` is generated by the DB.
export interface LogEntry {
    timestamp: string; // ISO 8601, as received
    level: LogLevel;
    service: string;
    message: string;
    attributes: Attributes;
}

// Per-entry ingestion outcome.
export interface RejectedEntry {
    index: number; // original position in the request batch
    reason: string;
}

export interface IngestResult {
    accepted: number;
    rejected: RejectedEntry[];
}

// Keyset pagination cursor payload: the (timestamp, id) of the last row seen.
export interface Cursor {
    timestamp: string;
    id: string;
}

// A parsed, validated query for GET /logs.
export interface QueryFilter {
    service?: string;
    level?: LogLevel;
    since?: string;   // ISO 8601, inclusive
    until?: string;   // ISO 8601, exclusive
    attributes: Record<string, string>; // attr.<key> = value (compared as string)
    q?: string;
    limit: number;    // 1..1000
    cursor?: Cursor;
}

// A log as returned by the API (id serialized as string).
export interface LogView {
    id: string;
    timestamp: string;
    level: string;
    service: string;
    message: string;
    attributes: Record<string, unknown>;
}

// GET /logs response.
export interface QueryResult {
    logs: LogView[];
    next_cursor: string | null;
}