// Domain types (see DESIGN.md §7). These mirror the API contract exactly.

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export type AttrValue = string | number | boolean;
export type Attributes = Record<string, AttrValue>;

// A validated log entry ready for persistence. `id` is generated by the DB.
export interface LogEntry {
    timestamp: string; // ISO 8601, as received
    level: LogLevel;
    service: string;
    message: string;
    attributes: Attributes;
}

// Per-entry ingestion outcome.
export interface RejectedEntry {
    index: number; // original position in the request batch
    reason: string;
}

export interface IngestResult {
    accepted: number;
    rejected: RejectedEntry[];
}