import type { Pool } from 'pg';
import type { Config } from '../config';

// Owns partition DDL (see DESIGN.md #5). Two responsibilities:
//   1. ensurePartitions(): create the daily partitions the service needs.
//   2. dropExpiredPartitions(): drop partitions fully outside the retention window (used later by the retention scheduler).
//
// CRITICAL: partition creation happens at startup + periodic maintenance ONLY,
// never inside the 15k/s ingestion hot path.

// How many days ahead to pre-create (covers day-boundary rollover + the allowed
// 5-minute future skew, with margin if maintenance is late).
const LOOK_AHEAD_DAYS = 2;

// Format a Date as YYYY-MM-DD in UTC (partition boundaries are UTC dates).
function utcDateString(d: Date): string {
    return d.toISOString().slice(0, 10); // "2026-08-17"
}

// Partition name for a given UTC day, e.g. logs_2026_08_17.
function partitionName(dateStr: string): string {
    return `logs_${dateStr.replace(/-/g, '_')}`;
}

// Add `days` to a date (UTC), returning a new Date at 00:00:00Z.
function addUtcDays(base: Date, days: number): Date {
    const d = new Date(Date.UTC(base.getUTCFullYear(), base.getUTCMonth(), base.getUTCDate()));
    d.setUTCDate(d.getUTCDate() + days);
    return d;
}

// Build the list of UTC day-start dates we want partitions for:
// from (today - retentionDays) through (today + lookAheadDays), inclusive.
function targetDays(now: Date, retentionDays: number): Date[] {
    const start = addUtcDays(now, -retentionDays);
    const end = addUtcDays(now, LOOK_AHEAD_DAYS);
    const days: Date[] = [];
    for (let d = start; d <= end; d = addUtcDays(d, 1)) {
        days.push(d);
    }
    return days;
}

// Create any missing daily partitions covering the retention window + look-ahead.
// Idempotent: CREATE TABLE IF NOT EXISTS skips ones that already exist.
//
// Note on safety: the date strings are generated by us (never user input) and
// pass through a strict YYYY-MM-DD shape, so building identifiers this way does
// not introduce injection. Values are still real dates, not concatenated input.
export async function ensurePartitions(
    pool: Pool,
    config: Config,
    now: Date = new Date(),
): Promise<string[]> {
    const created: string[] = [];

    for (const day of targetDays(now, config.retentionDays)) {
        const from = utcDateString(day);
        const to = utcDateString(addUtcDays(day, 1));
        const name = partitionName(from);

        // Defensive: reject anything that isn't exactly YYYY-MM-DD before it reaches SQL.
        if (!/^\d{4}-\d{2}-\d{2}$/.test(from) || !/^\d{4}-\d{2}-\d{2}$/.test(to)) {
            throw new Error(`Refusing to build partition for unsafe date range: ${from}..${to}`);
        }

        await pool.query(
            `CREATE TABLE IF NOT EXISTS ${name}
              PARTITION OF logs
              FOR VALUES FROM ('${from}') TO ('${to}')`,
        );
        created.push(name);
    }

    return created;
}

// Drop partitions whose entire day is older than the retention cutoff.
// Used by the retention scheduler (added in a later step).
export async function dropExpiredPartitions(
    pool: Pool,
    config: Config,
    now: Date = new Date(),
): Promise<string[]> {
    const cutoff = addUtcDays(now, -config.retentionDays);
    const dropped: string[] = [];

    // Find child partitions of `logs` and inspect their upper bound.
    const { rows } = await pool.query<{ child: string; bound: string }>(`
        SELECT c.relname AS child,
              pg_get_expr(c.relpartbound, c.oid) AS bound
        FROM pg_inherits i
        JOIN pg_class p ON p.oid = i.inhparent
        JOIN pg_class c ON c.oid = i.inhrelid
        WHERE p.relname = 'logs'
    `);

    for (const row of rows) {
        // bound looks like: FOR VALUES FROM ('2026-08-10') TO ('2026-08-11')
        const toMatch = row.bound.match(/TO \('([0-9-]+)/);
        if (!toMatch) continue;
        const upperExclusive = new Date(`${toMatch[1]}T00:00:00Z`);
        // If the partition's whole range ends at or before the cutoff, it's expired.
        if (upperExclusive <= cutoff) {
            // child name comes from the catalog (our own logs_YYYY_MM_DD), not user input.
            await pool.query(`DROP TABLE IF EXISTS ${row.child}`);
            dropped.push(row.child);
        }
    }

    return dropped;
}
